// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFg9Vi0lszYFFAp1tFEbCVPmOfjvJZIzg',
    appId: '1:66214617161:android:96d1a36276a6ff428c9f98',
    messagingSenderId: '66214617161',
    projectId: 'taufiq-sewa-motor',
    storageBucket: 'taufiq-sewa-motor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkJT_vz-401g_kcq1JkGbYWIlI3uiW1mM',
    appId: '1:66214617161:ios:1f142e54cc3168328c9f98',
    messagingSenderId: '66214617161',
    projectId: 'taufiq-sewa-motor',
    storageBucket: 'taufiq-sewa-motor.appspot.com',
    iosBundleId: 'com.taufiqsejati.motobike.cs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkJT_vz-401g_kcq1JkGbYWIlI3uiW1mM',
    appId: '1:66214617161:ios:1f142e54cc3168328c9f98',
    messagingSenderId: '66214617161',
    projectId: 'taufiq-sewa-motor',
    storageBucket: 'taufiq-sewa-motor.appspot.com',
    iosBundleId: 'com.taufiqsejati.motobike.cs',
  );
}
